### ISSUE TITLE
Feature Request for CT Calendar

### ISSUE THREAD

**Issue by David-its-me** [bensteUEM/ChurchToolsAPI#80]
Hello everybody,

I would like to ask for a new feature to retrieve entries from the ChurchTools Calendar. As far as I understood, at the moment it is only possible to poll events but not possible to retrieve calendar entries. 

We are already use some methods of this library in our church, to automatically generate slides with announcements on upcomming events. So from my side there would be high interest to have that feature. 
This means I could also contribute to the project, so please let me know if there is a way to work together. 

Sincerly
David

**Comment by bensteUEM** [comment]
You're right - we didn't implement calendar functions yet because it can be accessed using ICS feeds too.
I suppose you want to have access to 
- [ ] /calendars 
- [ ] /calendars/appointments
- [ ] /calendars/{calendarId}/appointments

Any other endpoints that are of interest?
(See e.g. https://elkw1610.krz.tools/api/)

I'm kinda busy with some other stuff at the moment, but if you're willing to contribute i'm more than happy arrange respective permissions for you. If you're lucky i might find some spare time during the next weeks and try to quickly add it.
In any case - thanks for adressing it as an issue here!

Do you prefer to wait or do you want to change it yourself?

**Comment by bensteUEM** [comment]
- [ ] Check if  'calculated' next to 'base' from results with multiple  appointments need to be included
- [] Check 'additionalInfos' and 'calculatedDates' for single appointment returns

**Comment by bensteUEM** [comment]
@David-its-me  - please have a look at the commit and let me know whether this functionality is sufficient for your use case
I still need to check the items listed above ....

**Comment by David-its-me** [comment]
I tested it a second ago. It perfecly matches my use case.
Thanks!

**Comment by bensteUEM** [comment]
Please don't close it just yet - I still need to merge it into a production release 😀

Thanks for testing,  glad it did support your purpose.

**Comment by bensteUEM** [comment]
- [ ] check how series of events are handled

**Comment by bensteUEM** [comment]
@David-its-me - startDate and endDate are now correctly calculated.
it is possible to get a series of appointments when using lookup by id - the result differs from the regular result.
additionalInfo is empty on my system - in case required by anybody i'd suggest opening another issue

**Comment by bensteUEM** [comment]
FYI - included in pre-release 1.5.2
